# Lighthouse-Badger-Easy | GitHub Action Workflow
# 
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL(s) to the current repository & main branch with minimal settings
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-badger-workflows
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Badger-Easy'

########################################################################
# DEFINE YOUR INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# INPUTS as environmental variables (env) for not manually triggered workflows 
env:
  URLS: https://thedannicraft.de # URL(s) to be checked e.g. 'https://github.com/sitdisch https://github.com/mythemeway'
  TOKEN_NAME: LIGHTHOUSE_BADGER_TOKEN # target token name; insert only the name never the real value e.g. 'LIGHTHOUSE_BADGER_TOKEN'
  # THAT'S IT; JUMP TO THE TRIGGERS;
  REPO_BRANCH: '${{ github.repository }} main' # target repo & branch

# TRIGGERS
on:
  page_build:
  schedule: # Check your schedule here => https://crontab.guru/
     - cron: '0 12 * * *' # e.g. every Sunday at 23:55
  # 
  # THAT'S IT; YOU'RE DONE;
